services:
  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    environment:
      - GO_ENV=development
      - DB_HOST=postgres
      - DB_NAME=notion_app
      - DB_USER=dev
      - DB_PASSWORD=dev123
      - DB_PORT=5432
      - DB_SSLMODE=disable
      - JWT_SECRET=your-secret-key-for-development
    depends_on:
      - postgres
    networks:
      - app-network

  # Database
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=notion_app
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge